// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type ImportJob struct {
	ID           string          `json:"id"`
	TenantID     string          `json:"tenantId"`
	RequestedBy  int             `json:"requestedBy"`
	Status       ImportJobStatus `json:"status"`
	CSVS3Key     string          `json:"csvS3Key"`
	ReportS3Key  *string         `json:"reportS3Key,omitempty"`
	TotalRows    *int            `json:"totalRows,omitempty"`
	PassedRows   *int            `json:"passedRows,omitempty"`
	FailedRows   *int            `json:"failedRows,omitempty"`
	ErrorMessage *string         `json:"errorMessage,omitempty"`
	CreatedAt    string          `json:"createdAt"`
	UpdatedAt    string          `json:"updatedAt"`
}

type ImportJobListPayload struct {
	Items []*ImportJobSummary `json:"items"`
	Total int                 `json:"total"`
}

type ImportJobSummary struct {
	ID           string          `json:"id"`
	TenantID     string          `json:"tenantId"`
	RequestedBy  int             `json:"requestedBy"`
	Status       ImportJobStatus `json:"status"`
	TotalRows    *int            `json:"totalRows,omitempty"`
	PassedRows   *int            `json:"passedRows,omitempty"`
	FailedRows   *int            `json:"failedRows,omitempty"`
	ErrorMessage *string         `json:"errorMessage,omitempty"`
	CreatedAt    string          `json:"createdAt"`
	UpdatedAt    string          `json:"updatedAt"`
}

type ImportUploadURLPayload struct {
	URL              string `json:"url"`
	JobID            string `json:"jobId"`
	ExpiresInSeconds int    `json:"expiresInSeconds"`
}

type Mutation struct {
}

type PresignedReportURL struct {
	URL              string `json:"url"`
	ExpiresInSeconds int    `json:"expiresInSeconds"`
}

type Query struct {
}

type StartImportPayload struct {
	JobID  string          `json:"jobId"`
	Status ImportJobStatus `json:"status"`
}

type ImportJobCreatedAtOrder string

const (
	ImportJobCreatedAtOrderAsc  ImportJobCreatedAtOrder = "ASC"
	ImportJobCreatedAtOrderDesc ImportJobCreatedAtOrder = "DESC"
)

var AllImportJobCreatedAtOrder = []ImportJobCreatedAtOrder{
	ImportJobCreatedAtOrderAsc,
	ImportJobCreatedAtOrderDesc,
}

func (e ImportJobCreatedAtOrder) IsValid() bool {
	switch e {
	case ImportJobCreatedAtOrderAsc, ImportJobCreatedAtOrderDesc:
		return true
	}
	return false
}

func (e ImportJobCreatedAtOrder) String() string {
	return string(e)
}

func (e *ImportJobCreatedAtOrder) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ImportJobCreatedAtOrder(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ImportJobCreatedAtOrder", str)
	}
	return nil
}

func (e ImportJobCreatedAtOrder) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ImportJobCreatedAtOrder) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ImportJobCreatedAtOrder) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ImportJobStatus string

const (
	ImportJobStatusPending    ImportJobStatus = "PENDING"
	ImportJobStatusAccepted   ImportJobStatus = "ACCEPTED"
	ImportJobStatusProcessing ImportJobStatus = "PROCESSING"
	ImportJobStatusCompleted  ImportJobStatus = "COMPLETED"
	ImportJobStatusFailed     ImportJobStatus = "FAILED"
)

var AllImportJobStatus = []ImportJobStatus{
	ImportJobStatusPending,
	ImportJobStatusAccepted,
	ImportJobStatusProcessing,
	ImportJobStatusCompleted,
	ImportJobStatusFailed,
}

func (e ImportJobStatus) IsValid() bool {
	switch e {
	case ImportJobStatusPending, ImportJobStatusAccepted, ImportJobStatusProcessing, ImportJobStatusCompleted, ImportJobStatusFailed:
		return true
	}
	return false
}

func (e ImportJobStatus) String() string {
	return string(e)
}

func (e *ImportJobStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ImportJobStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ImportJobStatus", str)
	}
	return nil
}

func (e ImportJobStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ImportJobStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ImportJobStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
