package main

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"time"

	"project-serverless/internal/domain"
)

// GetImportUploadURL is the resolver for the getImportUploadUrl field.
func (r *mutationResolver) GetImportUploadURL(ctx context.Context) (*ImportUploadURLPayload, error) {
	out, err := r.Orchestrator.GetImportUploadURL(ctx)
	if err != nil {
		return nil, err
	}
	return &ImportUploadURLPayload{
		URL:              out.URL,
		JobID:            out.JobID,
		ExpiresInSeconds: out.ExpiresInSeconds,
	}, nil
}

// StartImport is the resolver for the startImport field.
func (r *mutationResolver) StartImport(ctx context.Context, jobID string) (*StartImportPayload, error) {
	out, err := r.Orchestrator.StartImport(ctx, jobID)
	if err != nil {
		return nil, err
	}
	return &StartImportPayload{
		JobID:  out.JobID,
		Status: ImportJobStatus(out.Status),
	}, nil
}

// GetImportJob is the resolver for the getImportJob field.
func (r *queryResolver) GetImportJob(ctx context.Context, jobID string) (*ImportJob, error) {
	j, err := r.Orchestrator.GetImportJob(ctx, jobID)
	if err != nil {
		return nil, err
	}
	return mapImportJob(j), nil
}

// ListImportJobs is the resolver for the listImportJobs field.
func (r *queryResolver) ListImportJobs(ctx context.Context, skip *int, limit *int, status *ImportJobStatus, createdAtOrder *ImportJobCreatedAtOrder) (*ImportJobListPayload, error) {
	s := 0
	if skip != nil {
		s = *skip
	}
	l := 20
	if limit != nil && *limit > 0 {
		l = *limit
	}
	var st *string
	if status != nil {
		x := string(*status)
		st = &x
	}
	var ord *string
	if createdAtOrder != nil {
		x := string(*createdAtOrder)
		ord = &x
	}
	items, total, err := r.Orchestrator.ListImportJobs(ctx, s, l, st, ord)
	if err != nil {
		return nil, err
	}
	out := make([]*ImportJobSummary, 0, len(items))
	for i := range items {
		out = append(out, mapImportJobSummary(&items[i]))
	}
	t := int(total)
	return &ImportJobListPayload{Items: out, Total: t}, nil
}

// GetImportReportURL is the resolver for the getImportReportUrl field.
func (r *queryResolver) GetImportReportURL(ctx context.Context, jobID string) (*PresignedReportURL, error) {
	out, err := r.Orchestrator.GetImportReportURL(ctx, jobID)
	if err != nil {
		return nil, err
	}
	return &PresignedReportURL{
		URL:              out.URL,
		ExpiresInSeconds: out.ExpiresInSeconds,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

func mapImportJob(d *domain.ImportJob) *ImportJob {
	if d == nil {
		return nil
	}
	return &ImportJob{
		ID:           d.ID.String(),
		TenantID:     d.TenantID,
		RequestedBy:  d.RequestedBy,
		Status:       ImportJobStatus(d.Status),
		CSVS3Key:     d.CsvS3Key,
		ReportS3Key:  d.ReportS3Key,
		TotalRows:    d.TotalRows,
		PassedRows:   d.PassedRows,
		FailedRows:   d.FailedRows,
		ErrorMessage: d.ErrorMessage,
		CreatedAt:    d.CreatedAt.UTC().Format(time.RFC3339),
		UpdatedAt:    d.UpdatedAt.UTC().Format(time.RFC3339),
	}
}

func mapImportJobSummary(d *domain.ImportJob) *ImportJobSummary {
	if d == nil {
		return nil
	}
	return &ImportJobSummary{
		ID:           d.ID.String(),
		TenantID:     d.TenantID,
		RequestedBy:  d.RequestedBy,
		Status:       ImportJobStatus(d.Status),
		TotalRows:    d.TotalRows,
		PassedRows:   d.PassedRows,
		FailedRows:   d.FailedRows,
		ErrorMessage: d.ErrorMessage,
		CreatedAt:    d.CreatedAt.UTC().Format(time.RFC3339),
		UpdatedAt:    d.UpdatedAt.UTC().Format(time.RFC3339),
	}
}
