package main

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"strconv"
	"time"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, name string, email string) (*User, error) {
	domainUser, err := r.Orchestrator.CreateUser(ctx, name, email)
	if err != nil {
		return nil, err
	}

	return &User{
		ID:        strconv.Itoa(domainUser.ID),
		Name:      domainUser.Name,
		Email:     domainUser.Email,
		CreatedAt: domainUser.CreatedAt.Format(time.RFC3339),
	}, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, name string, email string) (*User, error) {
	domainUser, err := r.Orchestrator.UpdateUser(ctx, id, name, email)
	if err != nil {
		return nil, err
	}

	return &User{
		ID:        strconv.Itoa(domainUser.ID),
		Name:      domainUser.Name,
		Email:     domainUser.Email,
		CreatedAt: domainUser.CreatedAt.Format(time.RFC3339),
	}, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (*User, error) {
	domainUser, err := r.Orchestrator.DeleteUser(ctx, id)
	if err != nil {
		return nil, err
	}

	return &User{
		ID:        strconv.Itoa(domainUser.ID),
		Name:      domainUser.Name,
		Email:     domainUser.Email,
		CreatedAt: domainUser.CreatedAt.Format(time.RFC3339),
	}, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*User, error) {
	domainUser, err := r.Orchestrator.GetUser(ctx, id)
	if err != nil {
		return nil, err
	}

	return &User{
		ID:        strconv.Itoa(domainUser.ID),
		Name:      domainUser.Name,
		Email:     domainUser.Email,
		CreatedAt: domainUser.CreatedAt.Format(time.RFC3339),
	}, nil
}

// ListUsers is the resolver for the listUsers field.
func (r *queryResolver) ListUsers(ctx context.Context) ([]*User, error) {
	domainUsers, err := r.Orchestrator.ListUsers(ctx)
	if err != nil {
		return nil, err
	}

	users := make([]*User, 0, len(domainUsers))
	for _, domainUser := range domainUsers {
		u := domainUser
		users = append(users, &User{
			ID:        strconv.Itoa(u.ID),
			Name:      u.Name,
			Email:     u.Email,
			CreatedAt: u.CreatedAt.Format(time.RFC3339),
		})
	}
	return users, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
