DROP MATERIALIZED VIEW IF EXISTS read_model.users_summary CASCADE;
DROP TABLE IF EXISTS write_model.users CASCADE;
DROP SCHEMA IF EXISTS read_model CASCADE;
DROP SCHEMA IF EXISTS write_model CASCADE;
